version: '3.8'

services:
    backend:
      build: ./backend/
      image: backend-project-image
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=postgres
      ports:
        - 8080:8080
      container_name: backend
      depends_on:
        - db
    frontend:
      build: ./frontend/
      image: frontend-project-image
      ports:
        - 5000:5000
      container_name: frontend
    redis:
      image: redis:alpine
      container_name: redis
    db:
      image: postgres:13.2-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      volumes:
        - ./database:/var/lib/postgresql/data

volumes:
  database:
