version: '3.8'

services:

    backend:
      build: ./backend/
      image: backend-project-image
      environment:
        - REDIS_HOST=redis
      ports:
        - 8080:8080
      container_name: backend
    
    frontend:
      build: ./frontend/
      image: frontend-project-image
      ports:
        - 5000:5000
      container_name: frontend
    
    redis:
      image: redis:alpine
      container_name: redis
