version: '3.8'

services:
    backend:
      build: ./backend/
      image: backend-project-image
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DATABASE=postgres
        - REQUEST_ORIGIN=http://localhost
      container_name: backend
      depends_on:
        - db
    frontend:
      build: ./frontend/
      image: frontend-project-image
      container_name: frontend
    redis:
      image: redis:alpine
      container_name: redis
    db:
      image: postgres:13.2-alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      volumes:
        - ./database:/var/lib/postgresql/data
    nginx:
      image: nginx:1.19-alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - backend
        - frontend
      ports:
        - 80:80
volumes:
  database:
